dataset: "Frysk_CV"

path:
  corpus_path: "../corpus_frisian/30-speakers"
  lexicon_path: "./config/Frysk_CV/Frysk_CV.dict"
  raw_path: "../corpus_frisian/30-speakers"
  preprocessed_path: "./preprocessed_data/Frysk_CV"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "fy"
  audio:
    sampling_rate: 22050
    max_wav_value: 32767
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
